---

- name: Install NFS client packages
  ansible.builtin.apt:
    name: nfs-common
    state: present
    update_cache: yes

- name: Check if /mnt/nfs exists
  stat:
    path: /mnt/nfs
  register: nfs_dir_stat

- name: Create NFS mount point if it doesn't exist
  file:
    path: "{{ local_mount_point }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  when: not nfs_dir_stat.stat.exists

- name: Mount an NFS volume
  ansible.posix.mount:
    src: "{{ nfs_server_ip }}:{{ nfs_shared_dir }}"
    path: "{{ local_mount_point }}"
    opts: "{{ mount_options }}"
    state: mounted
    fstype: nfs

#- name: Update /etc/fstab to ensure persistent mount
#  template:
#    src: fstab.j2
#    dest: /etc/fstab
#    owner: root
#    group: root
#    mode: '0644'
#  notify: Remount NFS

- name: Backup fstab 
  ansible.builtin.copy:
    src: /etc/fstab
    dest: /etc/fstab.bkp
    owner: root
    group: root
    mode: '0644'

- name: "Add mount to /etc/fstab"
  lineinfile:
    path: '/etc/fstab'
    line: "{{ nfs_server_ip }}:{{ nfs_shared_dir }} {{ local_mount_point }} nfs {{ mount_options }} 0 0"
  notify: Remount NFS
...
