---
- name: Add application user
  community.mysql.mysql_user:
    name: "{{ mysql_app_user }}"
    password: "{{ mysql_app_user_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    host: "%"
    state: present

- name: Create a MySQL database for cms wp
  community.mysql.mysql_db:
    name: "{{ mysql_wp_db_name }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    state: present

- name: Grant all privileges on wp_database for application user
  community.mysql.mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    user: "{{ mysql_app_user }}"
    host: "%"
    priv: "{{ mysql_wp_db_name }}.*:ALL"
    state: present

- name: Add backup user
  community.mysql.mysql_user:
    name: "{{ mysql_backup_user }}"
    password: "{{ mysql_backup_user_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    host: "%"
    priv: "{{ mysql_backup_privileges }}"
    state: present

- name: Grant privileges for backup user
  community.mysql.mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    user: "{{ mysql_backup_user }}"
    host: "%"
    priv: "{{ mysql_backup_privileges }}"
    state: present

...
