---
- name: Restart_mysql_service
  service:
    name: mysql
    state: restarted
  become: yes

- name: Flush_privileges
  community.mysql.mysql_query:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    query: "FLUSH PRIVILEGES"
...
