---
- name: Install prometheus package
  ansible.builtin.apt:
    name: prometheus

- name: Copy prometheus config file
  copy:
    src: prometheus.yml 
    dest: /etc/prometheus
    owner: root
    group: root
    mode: '0644'
  notify: Restart_prometheus_service

- name: Restart prometheus service
  ansible.builtin.systemd:
    name: prometheus
    state: restarted

- name: Install grafana package
  ansible.builtin.apt:
    deb: "//mnt/nfs/install/prmt/grafana_11.3.0_amd64.deb"

- name: Ensure Grafana service is running and enabled
  ansible.builtin.systemd:
    name: grafana-server
    state: started
    enabled: yes

- name: Wait for Grafana to start
  ansible.builtin.wait_for:
    port: 3000
    timeout: 60

- name: Fix broken dependencies and remove unused packages
  ansible.builtin.apt:
    state: fixed
    autoremove: yes

- name: Upload grafana config
  template:
    src: "{{grafana_config_template}}"
    dest: "{{grafana_config_directory}}/grafana.ini"
    owner: "root"
    group: "grafana"
    mode: 0640

- name: Upload grafana prometheus datasource config yml
  template:
    src: "{{grafana_datasource_template}}"
    dest: "{{grafana_config_directory}}/provisioning/datasources/{{grafana_datasource_template}}"
    owner: "root"
    group: "grafana"
    mode: 0640
  notify: Restart_grafana_service

- name: Copy scripts folder to prmt server
  ansible.builtin.copy:
    src: /mnt/nfs/bkp/prmt/ubuntu07/scripts
    dest: /scripts/
    owner: root
    group: root
    mode: 0644
  run_once: true
...
