---
- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Start and enable nginx service
  ansible.builtin.systemd:
    name: nginx.service
    enabled: yes
    state: started

- name: Copy config file to lb
  copy:
    src: default
    dest: /etc/nginx/sites-available/
    owner: root
    group: root
    mode: 0644
  notify: Restart_nginx
...
