---
- name: Create ansible user
  ansible.builtin.user:
    name: ansible
    group: root
    state: present
    shell: /bin/bash

- name: Add ssh key for ansible
  ansible.builtin.authorized_key:
    user: ansible
    state: present
    key: "{{ lookup('file', '/home/user01/.ssh/ansible.pub') }}"
#    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK18OB5n2z9hKeNT9Xs0x03Y4DmL97DlNFTLUJJT1I2C ansible"

- name: Add sudoers file for ansible
  copy:
    src: sudoer_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440

- name: Generate sshd_config file from template
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: Restart_sshd

- name: Update and upgrade apt packages
  ansible.builtin.apt:
    update_cache: yes
    upgrade: "safe"

- name: Set TimeZone
  timezone:
    name: Europe/Moscow

- name: Install prometheus node exporter
  ansible.builtin.apt:
    name: prometheus-node-exporter
    state: present

- name: Install mc
  ansible.builtin.apt:
    name: mc
    state: present

- name: Install sshpass
  ansible.builtin.apt:
    name: sshpass
    state: present

...
